# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9e880f0acedc2be4b5f84614f41ce3012aa82f8055f63f477afc7c1d57baf0b811090a9d1f537d7bf007b9bd176afae2bafa08d3240acc7f19c9b88be2fa516

test:
  secret_key_base: 2e8df816fb3fcf8b374098a08eca05d8a0b9a1c965836fa4dd795a9d8fc1c14b1563f3fe6e1bdc9dc900c4f4b7ca6c31dfece1eb893df36cf4dae8ea53bf93ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
